# Generated by Django 5.2.6 on 2026-02-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0012_alter_muestra_estado_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='estado_actual',
            field=models.CharField(blank=True, choices=[('DISP', 'Disponible'), ('ENV', 'Enviada'), ('PENV', 'Parcialmente enviada'), ('DEST', 'Destruida')], default='DISP', help_text='Disponible por defecto', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='fecha_extraccion',
            field=models.DateField(blank=True, help_text='Fecha de extracción de la muestra, en formato AAAA-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='fecha_llegada',
            field=models.DateField(blank=True, help_text='Fecha de llegada de la muestra, en formato AAAA-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='id_individuo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='id_material',
            field=models.CharField(blank=True, help_text='Material de la muestra', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='nom_lab',
            field=models.CharField(help_text='Nombre único de la muestra asignado por el laboratorio', max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(fields=('rack', 'posicion_caja_rack'), name='unique_posicion_caja_por_rack'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('estante', 'posicion_rack_estante'), name='unique_posicion_rack_por_estante'),
        ),
    ]
