# Generated by Django 5.2.6 on 2026-02-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0013_alter_muestra_estado_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='fecha_extraccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='fecha_llegada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
